Repository InterfaceX-co-jp/frourio-framework-prisma-generators, pull requests merged in 2024-12, with the labels that each got.

#36 refactor: Use union for both with and without include
  src/generators/model/transformer.ts
Labels: bug

#38 fix: Prisma nesting include type
  src/generators/model/transformer.ts
Labels: bug, feature

#40 fix: Make includes optional
  package-lock.json
  package.json
  package/package.json
  src/generators/model/transformer.ts
Labels: bug

#41 refactor: simplify type definition handling in Transformer class by i…
  package-lock.json
  package.json
  package/package.json
  src/generators/model/transformer.ts
Labels: bug

#43 fix:Allow null and undefined values for fields of type "DateTime"
  src/generators/model/transformer.ts
Labels: bug

#44 feat:prevent model duplication
  prisma/schema.prisma
  src/generators/model/transformer.ts
Labels: feature
